# # -*- coding: utf-8 -*-

# # Form implementation generated from reading ui file 'untitled.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.9
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.

# from PyQt5 import QtCore, QtGui, QtWidgets


# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(800, 600)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
        
#         # Define the rounded corner style
#         label_style = "background-color: rgb(78, 154, 6); border-radius: 10px; padding: 5px; color: white; font-weight: bold;"
        
#         # Create labels and set text
#         self.label_01 = QtWidgets.QLabel(self.centralwidget)
#         self.label_01.setGeometry(QtCore.QRect(80, 70, 91, 31))
#         self.label_01.setStyleSheet(label_style)
#         self.label_01.setObjectName("label_01")
#         self.label_01.setText("Label 01")
        
#         self.label_02 = QtWidgets.QLabel(self.centralwidget)
#         self.label_02.setGeometry(QtCore.QRect(80, 110, 91, 31))
#         self.label_02.setStyleSheet(label_style)
#         self.label_02.setObjectName("label_02")
#         self.label_02.setText("Label 02")
        
#         self.label_03 = QtWidgets.QLabel(self.centralwidget)
#         self.label_03.setGeometry(QtCore.QRect(80, 150, 91, 31))
#         self.label_03.setStyleSheet(label_style)
#         self.label_03.setObjectName("label_03")
#         self.label_03.setText("Label 03")
        
#         self.label_05 = QtWidgets.QLabel(self.centralwidget)
#         self.label_05.setGeometry(QtCore.QRect(80, 230, 91, 31))
#         self.label_05.setStyleSheet(label_style)
#         self.label_05.setObjectName("label_05")
#         self.label_05.setText("Label 05")
        
#         self.label_04 = QtWidgets.QLabel(self.centralwidget)
#         self.label_04.setGeometry(QtCore.QRect(80, 190, 91, 31))
#         self.label_04.setStyleSheet(label_style)
#         self.label_04.setObjectName("label_04")
#         self.label_04.setText("Label 04")
        
#         self.label_06 = QtWidgets.QLabel(self.centralwidget)
#         self.label_06.setGeometry(QtCore.QRect(80, 270, 91, 31))
#         self.label_06.setStyleSheet(label_style)
#         self.label_06.setObjectName("label_06")
#         self.label_06.setText("Label 06")
        
#         self.label_10 = QtWidgets.QLabel(self.centralwidget)
#         self.label_10.setGeometry(QtCore.QRect(80, 430, 91, 31))
#         self.label_10.setStyleSheet(label_style)
#         self.label_10.setObjectName("label_10")
#         self.label_10.setText("Label 10")
        
#         self.label_08 = QtWidgets.QLabel(self.centralwidget)
#         self.label_08.setGeometry(QtCore.QRect(80, 350, 91, 31))
#         self.label_08.setStyleSheet(label_style)
#         self.label_08.setObjectName("label_08")
#         self.label_08.setText("Label 08")
        
#         self.label_07 = QtWidgets.QLabel(self.centralwidget)
#         self.label_07.setGeometry(QtCore.QRect(80, 310, 91, 31))
#         self.label_07.setStyleSheet(label_style)
#         self.label_07.setObjectName("label_07")
#         self.label_07.setText("Label 07")
        
#         self.label_09 = QtWidgets.QLabel(self.centralwidget)
#         self.label_09.setGeometry(QtCore.QRect(80, 390, 91, 31))
#         self.label_09.setStyleSheet(label_style)
#         self.label_09.setObjectName("label_09")
#         self.label_09.setText("Label 09")
        
#         self.label_14 = QtWidgets.QLabel(self.centralwidget)
#         self.label_14.setGeometry(QtCore.QRect(250, 190, 91, 31))
#         self.label_14.setStyleSheet(label_style)
#         self.label_14.setObjectName("label_14")
#         self.label_14.setText("Label 14")
        
#         self.label_19 = QtWidgets.QLabel(self.centralwidget)
#         self.label_19.setGeometry(QtCore.QRect(250, 390, 91, 31))
#         self.label_19.setStyleSheet(label_style)
#         self.label_19.setObjectName("label_19")
#         self.label_19.setText("Label 19")
        
#         self.label_12 = QtWidgets.QLabel(self.centralwidget)
#         self.label_12.setGeometry(QtCore.QRect(250, 110, 91, 31))
#         self.label_12.setStyleSheet(label_style)
#         self.label_12.setObjectName("label_12")
#         self.label_12.setText("Label 12")
        
#         self.label_20 = QtWidgets.QLabel(self.centralwidget)
#         self.label_20.setGeometry(QtCore.QRect(250, 430, 91, 31))
#         self.label_20.setStyleSheet(label_style)
#         self.label_20.setObjectName("label_20")
#         self.label_20.setText("Label 20")
        
#         self.label_16 = QtWidgets.QLabel(self.centralwidget)
#         self.label_16.setGeometry(QtCore.QRect(250, 270, 91, 31))
#         self.label_16.setStyleSheet(label_style)
#         self.label_16.setObjectName("label_16")
#         self.label_16.setText("Label 16")
        
#         self.label_18 = QtWidgets.QLabel(self.centralwidget)
#         self.label_18.setGeometry(QtCore.QRect(250, 350, 91, 31))
#         self.label_18.setStyleSheet(label_style)
#         self.label_18.setObjectName("label_18")
#         self.label_18.setText("Label 18")
        
#         self.label_15 = QtWidgets.QLabel(self.centralwidget)
#         self.label_15.setGeometry(QtCore.QRect(250, 230, 91, 31))
#         self.label_15.setStyleSheet(label_style)
#         self.label_15.setObjectName("label_15")
#         self.label_15.setText("Label 15")
        
#         self.label_11 = QtWidgets.QLabel(self.centralwidget)
#         self.label_11.setGeometry(QtCore.QRect(250, 70, 91, 31))
#         self.label_11.setStyleSheet(label_style)
#         self.label_11.setObjectName("label_11")
#         self.label_11.setText("Label 11")
        
#         self.label_13 = QtWidgets.QLabel(self.centralwidget)
#         self.label_13.setGeometry(QtCore.QRect(250, 150, 91, 31))
#         self.label_13.setStyleSheet(label_style)
#         self.label_13.setObjectName("label_13")
#         self.label_13.setText("Label 13")
        
#         self.label_17 = QtWidgets.QLabel(self.centralwidget)
#         self.label_17.setGeometry(QtCore.QRect(250, 310, 91, 31))
#         self.label_17.setStyleSheet(label_style)
#         self.label_17.setObjectName("label_17")
#         self.label_17.setText("Label 17")
        
#         self.label_21 = QtWidgets.QLabel(self.centralwidget)
#         self.label_21.setGeometry(QtCore.QRect(420, 70, 91, 31))
#         self.label_21.setStyleSheet(label_style)
#         self.label_21.setObjectName("label_21")
#         self.label_21.setText("Label 21")
        
#         self.label_27 = QtWidgets.QLabel(self.centralwidget)
#         self.label_27.setGeometry(QtCore.QRect(420, 310, 91, 31))
#         self.label_27.setStyleSheet(label_style)
#         self.label_27.setObjectName("label_27")
#         self.label_27.setText("Label 27")
        
#         self.label_29 = QtWidgets.QLabel(self.centralwidget)
#         self.label_29.setGeometry(QtCore.QRect(420, 390, 91, 31))
#         self.label_29.setStyleSheet(label_style)
#         self.label_29.setObjectName("label_29")
#         self.label_29.setText("Label 29")
        
#         self.label_28 = QtWidgets.QLabel(self.centralwidget)
#         self.label_28.setGeometry(QtCore.QRect(420, 350, 91, 31))
#         self.label_28.setStyleSheet(label_style)
#         self.label_28.setObjectName("label_28")
#         self.label_28.setText("Label 28")
        
#         self.label_30 = QtWidgets.QLabel(self.centralwidget)
#         self.label_30.setGeometry(QtCore.QRect(420, 430, 91, 31))
#         self.label_30.setStyleSheet(label_style)
#         self.label_30.setObjectName("label_30")
#         self.label_30.setText("Label 30")
        
#         self.label_24 = QtWidgets.QLabel(self.centralwidget)
#         self.label_24.setGeometry(QtCore.QRect(420, 190, 91, 31))
#         self.label_24.setStyleSheet(label_style)
#         self.label_24.setObjectName("label_24")
#         self.label_24.setText("Label 24")
        
#         self.label_25 = QtWidgets.QLabel(self.centralwidget)
#         self.label_25.setGeometry(QtCore.QRect(420, 230, 91, 31))
#         self.label_25.setStyleSheet(label_style)
#         self.label_25.setObjectName("label_25")
#         self.label_25.setText("Label 25")
        
#         self.label_26 = QtWidgets.QLabel(self.centralwidget)
#         self.label_26.setGeometry(QtCore.QRect(420, 270, 91, 31))
#         self.label_26.setStyleSheet(label_style)
#         self.label_26.setObjectName("label_26")
#         self.label_26.setText("Label 26")
        
#         self.label_23 = QtWidgets.QLabel(self.centralwidget)
#         self.label_23.setGeometry(QtCore.QRect(420, 150, 91, 31))
#         self.label_23.setStyleSheet(label_style)
#         self.label_23.setObjectName("label_23")
#         self.label_23.setText("Label 23")
        
#         self.label_22 = QtWidgets.QLabel(self.centralwidget)
#         self.label_22.setGeometry(QtCore.QRect(420, 110, 91, 31))
#         self.label_22.setStyleSheet(label_style)
#         self.label_22.setObjectName("label_22")
#         self.label_22.setText("Label 22")
        
#         self.label_31 = QtWidgets.QLabel(self.centralwidget)
#         self.label_31.setGeometry(QtCore.QRect(600, 70, 91, 31))
#         self.label_31.setStyleSheet(label_style)
#         self.label_31.setObjectName("label_31")
#         self.label_31.setText("Label 31")
        
#         self.label_32 = QtWidgets.QLabel(self.centralwidget)
#         self.label_32.setGeometry(QtCore.QRect(600, 110, 91, 31))
#         self.label_32.setStyleSheet(label_style)
#         self.label_32.setObjectName("label_32")
#         self.label_32.setText("Label 32")
        
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
#         self.menubar.setObjectName("menubar")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)

#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)

#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         # Labels are already set via the setText() method, so no need to manually update them here


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())


# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        
        # Central widget setup
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Define the rounded corner style for labels
        label_style = "background-color: rgb(78, 154, 6); border-radius: 10px; padding: 5px; color: white; font-weight: bold;"

        # Create a QGridLayout to arrange the labels
        grid_layout = QtWidgets.QGridLayout(self.centralwidget)
        grid_layout.setObjectName("grid_layout")
        
        # Set spacing and margins for better positioning
        grid_layout.setSpacing(10)  # Add space between the widgets
        grid_layout.setContentsMargins(20, 20, 20, 20)  # Set margins around the grid
        
        # Add labels to the grid layout in a specific row and column
        self.label_01 = self.createLabel("Label 01", label_style)
        grid_layout.addWidget(self.label_01, 0, 0)

        self.label_02 = self.createLabel("Label 02", label_style)
        grid_layout.addWidget(self.label_02, 1, 0)

        self.label_03 = self.createLabel("Label 03", label_style)
        grid_layout.addWidget(self.label_03, 2, 0)

        self.label_04 = self.createLabel("Label 04", label_style)
        grid_layout.addWidget(self.label_04, 3, 0)

        self.label_05 = self.createLabel("Label 05", label_style)
        grid_layout.addWidget(self.label_05, 4, 0)

        self.label_06 = self.createLabel("Label 06", label_style)
        grid_layout.addWidget(self.label_06, 5, 0)

        self.label_07 = self.createLabel("Label 07", label_style)
        grid_layout.addWidget(self.label_07, 6, 0)

        self.label_08 = self.createLabel("Label 08", label_style)
        grid_layout.addWidget(self.label_08, 7, 0)

        self.label_09 = self.createLabel("Label 09", label_style)
        grid_layout.addWidget(self.label_09, 8, 0)

        self.label_10 = self.createLabel("Label 10", label_style)
        grid_layout.addWidget(self.label_10, 9, 0)

        self.label_11 = self.createLabel("Label 11", label_style)
        grid_layout.addWidget(self.label_11, 0, 1)

        self.label_12 = self.createLabel("Label 12", label_style)
        grid_layout.addWidget(self.label_12, 1, 1)

        self.label_13 = self.createLabel("Label 13", label_style)
        grid_layout.addWidget(self.label_13, 2, 1)

        self.label_14 = self.createLabel("Label 14", label_style)
        grid_layout.addWidget(self.label_14, 3, 1)

        self.label_15 = self.createLabel("Label 15", label_style)
        grid_layout.addWidget(self.label_15, 4, 1)

        self.label_16 = self.createLabel("Label 16", label_style)
        grid_layout.addWidget(self.label_16, 5, 1)

        self.label_17 = self.createLabel("Label 17", label_style)
        grid_layout.addWidget(self.label_17, 6, 1)

        self.label_18 = self.createLabel("Label 18", label_style)
        grid_layout.addWidget(self.label_18, 7, 1)

        self.label_19 = self.createLabel("Label 19", label_style)
        grid_layout.addWidget(self.label_19, 8, 1)

        self.label_20 = self.createLabel("Label 20", label_style)
        grid_layout.addWidget(self.label_20, 9, 1)

        self.label_21 = self.createLabel("Label 21", label_style)
        grid_layout.addWidget(self.label_21, 0, 2)

        self.label_22 = self.createLabel("Label 22", label_style)
        grid_layout.addWidget(self.label_22, 1, 2)

        self.label_23 = self.createLabel("Label 23", label_style)
        grid_layout.addWidget(self.label_23, 2, 2)

        self.label_24 = self.createLabel("Label 24", label_style)
        grid_layout.addWidget(self.label_24, 3, 2)

        self.label_25 = self.createLabel("Label 25", label_style)
        grid_layout.addWidget(self.label_25, 4, 2)

        self.label_26 = self.createLabel("Label 26", label_style)
        grid_layout.addWidget(self.label_26, 5, 2)

        self.label_27 = self.createLabel("Label 27", label_style)
        grid_layout.addWidget(self.label_27, 6, 2)

        self.label_28 = self.createLabel("Label 28", label_style)
        grid_layout.addWidget(self.label_28, 7, 2)

        self.label_29 = self.createLabel("Label 29", label_style)
        grid_layout.addWidget(self.label_29, 8, 2)

        self.label_30 = self.createLabel("Label 30", label_style)
        grid_layout.addWidget(self.label_30, 9, 2)

        self.label_31 = self.createLabel("Label 31", label_style)
        grid_layout.addWidget(self.label_31, 0, 3)

        self.label_32 = self.createLabel("Label 32", label_style)
        grid_layout.addWidget(self.label_32, 1, 3)

        # Set the grid layout as the layout for the central widget
        self.centralwidget.setLayout(grid_layout)
        
        # Set the central widget for the main window
        MainWindow.setCentralWidget(self.centralwidget)

        # Set up menu bar and status bar (not the focus here)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Final setup
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def createLabel(self, text, style):
        label = QtWidgets.QLabel(self.centralwidget)
        label.setStyleSheet(style)
        label.setText(text)
        return label


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
